import Link from "next/link";
import DirectoryArchiveButton from "@/components/directory/DirectoryArchiveButton";
import Breadcrumbs from "@/components/ui/Breadcrumbs";
import EmptyState from "@/components/ui/EmptyState";
import PageContainer from "@/components/layout/PageContainer";
import { requireUser } from "@/lib/auth/require-user";
import { directoryLocation, getDirectoryEntriesForOwner } from "@/lib/supabase/directory";

export default async function MyDirectoryEntriesPage() {
  const user = await requireUser("/directory/mine");
  const entries = await getDirectoryEntriesForOwner(user.id);
  return <main className="bg-[#e8dfd3] py-12 sm:py-16"><PageContainer><div className="mx-auto max-w-4xl"><Breadcrumbs items={[{ label: "Directory", href: "/directory" }, { label: "My listings" }]} /><p className="mt-8 text-[0.6875rem] font-bold uppercase tracking-[0.22em] text-[#7b2430]">My directory listings</p><h1 className="mt-4 font-serif text-5xl tracking-[-0.045em] text-[#242721] sm:text-6xl">Your entries.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-[#56584f]">Track drafts, submissions in review, published listings, and archived entries.</p>{entries.length > 0 ? <div className="mt-8 space-y-4">{entries.map((entry) => <article key={entry.id} className="flex flex-col gap-4 border border-[#242721]/20 bg-[#f9f5ed] p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[0.6875rem] font-bold uppercase tracking-[0.14em] text-[#7b2430]">{entry.moderation_status}</p><h2 className="mt-2 font-serif text-2xl text-[#242721]"><Link href={`/directory/${entry.slug}`} className="transition-colors hover:text-[#7b2430]">{entry.name}</Link></h2><p className="mt-1 text-sm text-[#56584f]">{directoryLocation(entry)}</p></div><div className="flex flex-wrap gap-3"><Link href={`/directory/${entry.slug}/edit`} className="inline-flex border border-[#2d4737] px-3 py-2 text-sm font-bold text-[#2d4737] transition-colors hover:border-[#7b2430] hover:text-[#7b2430]">Edit</Link>{entry.moderation_status !== "archived" ? <DirectoryArchiveButton entryId={entry.id} /> : null}</div></article>)}</div> : <div className="mt-8"><EmptyState eyebrow="Your book is clear" title="No directory listings are attached to this account." description="Add a listing when the details are ready to share." action={<Link href="/directory/new" className="inline-flex border-b border-[#2d4737] pb-1 text-sm font-bold text-[#2d4737] transition-colors hover:border-[#7b2430] hover:text-[#7b2430]">Add a directory listing <span className="ml-2" aria-hidden="true">↗</span></Link>} /></div>}</div></PageContainer></main>;
}
