import Link from "next/link";
import EmptyState from "@/components/ui/EmptyState";
import PageContainer from "@/components/layout/PageContainer";
import { reviewTargetFromRow, getPublishedReviews } from "@/lib/supabase/reviews";
import { reviewTargetLabel } from "@/lib/relationships";

export default async function ReviewsPage() {
  const reviews = await getPublishedReviews();
  return <main className="bg-[#f4efe5] py-12 sm:py-16"><PageContainer><header className="max-w-3xl border-b border-[#242721]/20 pb-8"><p className="text-[0.6875rem] font-bold uppercase tracking-[0.22em] text-[#7b2430]">References and reviews</p><h1 className="mt-4 font-serif text-5xl tracking-[-0.045em] text-[#242721] sm:text-6xl">The useful kind of horse-world feedback.</h1><p className="mt-5 text-lg leading-8 text-[#56584f]">Clear, moderated notes connected to a real listing, service, shipper, event, or directory identity.</p><Link href="/reviews/mine" className="mt-7 inline-flex border border-[#2d4737] px-4 py-2.5 text-sm font-bold text-[#2d4737] hover:border-[#7b2430] hover:text-[#7b2430]">Manage my reviews</Link></header>{reviews.length > 0 ? <section className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{reviews.map((review) => { const target = reviewTargetFromRow(review); return <article key={review.id} className="border border-[#242721]/20 bg-[#f9f5ed] p-5"><p className="text-[0.6875rem] font-bold uppercase tracking-[0.14em] text-[#7b2430]">{target ? reviewTargetLabel(target.type) : "Review"}</p><p className="mt-4 text-sm tracking-[0.16em] text-[#b08d57]" aria-label={`${review.rating} out of 5 stars`}>{"★".repeat(review.rating)}{"☆".repeat(5 - review.rating)}</p>{review.title ? <h2 className="mt-3 font-serif text-2xl text-[#242721]">{review.title}</h2> : null}<p className="mt-3 line-clamp-5 text-sm leading-7 text-[#56584f]">{review.body}</p></article>; })}</section> : <div className="mt-10"><EmptyState eyebrow="The reference book is clear" title="No approved reviews are posted." description="Reviews begin from the listing, event, provider, or route they are actually about." action={<Link href="/directory" className="inline-flex border-b border-[#2d4737] pb-1 text-sm font-bold text-[#2d4737]">Browse the directory</Link>} /></div>}</PageContainer></main>;
}
